quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,origin,x-requested-with
quarkus.http.cors.access-control-max-age=24H

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=594741
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mini_oj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
app.jwt.secret=I_am_a_jwt
app.jwt.expire-seconds=720011111111
go-judge.base-url=http://101.126.143.157:5050
