quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=594741
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mini_oj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
app.jwt.secret=I_am_a_jwt
app.jwt.expire-seconds=720011111111
